Adding tables to readme
openmc-dev/data pull request #47
Opened 2020-10-22 17:02 UTC by Shimwell

Just adding a little table to the readme as a guide that shows what we have covered and the different options for downloading

Also I noticed the https://openmc.mcs.anl.gov/ website as two scripts for JEFF 3.3, just wondering if there is a difference

2020-11-04 20:07 UTC, paulromano requested changes
This is a little misleading because the "MCNP" libraries are actually ENDF/B. It's just that we have multiple ENDF/B libraries (one processed by LANL, one processed by NNDC, one processed by us). Maybe have another column to indicate what organization did the processing?

Also you can use the much nicer openmc.org instead of openmc.mcs.anl.gov.

2020-11-05 10:47 UTC, Shimwell commented on README.md
> +| Library | Release | Download from [openmc.mcs.anl.gov](https://openmc.mcs.anl.gov/) | Download ACE files and convert HDF5 | Download ENDF files and generate HDF5 | Convert local ACE files |
```suggestion
| Library | Release | Download from [openmc.org](https://openmc.org/) | Download ACE files and convert HDF5 | Download ENDF files and generate HDF5 | Convert local ACE files |
```

2020-11-05 11:08 UTC, Shimwell commented
Had a go at adding the processed by column. I think I have confused myself as well in the process. But perhaps it is a little closer

2020-11-09 21:38 UTC, Shimwell commented
Also I noticed there is reference to a openmc-get-multipole-data in the openmc docs https://docs.openmc.org/en/latest/examples/nuclear-data.html#Windowed-multipole

This script does not feature in the table and is not in the data repository but perhaps it should? 

Perhaps good to mention this repo somewhere in the data repository README https://github.com/mit-crpg/WMP_Library

2020-11-10 13:50 UTC, paulromano commented on README.md
> +| ENDF | B-VIII.0 | NNDC | :heavy_check_mark: |  | generate_endf80.py |  |
```suggestion
| ENDF/B | VII.0 | LANL | :heavy_check_mark: |  |  | convert_mcnp70.py |
| ENDF/B | VII.1 | LANL | :heavy_check_mark: |  |  | convert_mcnp71.py |
| ENDF/B | VII.1 | NNDC | :heavy_check_mark: | convert_nndc71.py | generate_endf71.py |  |
| ENDF/B | VIII.0 | LANL | :heavy_check_mark: |  |  | convert_lib80x.py |
| ENDF/B | VIII.0 | NNDC | :heavy_check_mark: |  | generate_endf80.py |  |
```

2020-11-10 13:51 UTC, paulromano commented
`openmc-get-multipole-data` hasn't existed for quite some time. It was removed after the library itself was made available at the github repo you've mentioned. Probably a good idea to mention it on the readme!

2020-11-10 15:17 UTC, Shimwell commented on README.md
> +| ENDF | B-VIII.0 | NNDC | :heavy_check_mark: |  | generate_endf80.py |  |
Thanks

2020-11-11 04:23 UTC, paulromano requested changes
Two more nitpicks here and I think we're done :smile: Thanks @Shimwell!

2020-11-11 04:23 UTC, paulromano commented on README.md
> +https://openmc.mcs.anl.gov. Another source of data libraries for OpenMC is the
```suggestion
https://openmc.org. Another source of data libraries for OpenMC is the
```

2020-11-11 04:23 UTC, paulromano commented on README.md
> +repository which allows on-the-fly Doppler broadening to an arbitrary
```suggestion
repository which enables on-the-fly Doppler broadening to an arbitrary
```

2020-11-11 12:01 UTC, paulromano approved these changes

2020-11-11 12:01 UTC, merged